version: '3.16'

services:
    bootstrapper:
        build: .
        env_file: .env

    learncoind:
        build: .
        depends_on:
            - bootstrapper
        env_file: .env
        environment:
            - BOOTSTRAP_NODE=bootstrapper:8080
        #ports:
            #- '5000:5000'